require('./unit/utils.test.js')
require('./unit/tmdb.test.js')
require('./unit/balances.test.js')
require('./unit/address.test.js')
require('./unit/accounts.test.js')
require('./unit/transactions.test.js')
require('./unit/delegates.test.js')
require('./unit/miscellaneous.test.js')
require('./unit/peers.blocks.test.js')
require('./unit/peers.transactions.test.js')
require('./unit/peers.secondpassword.test.js')
require('./unit/peers.delegates.test.js')
require('./unit/peers.votes.test.js')

require('./unit/amount.test.js')
require('./unit/multinodes.test.js')
require('./unit/limit-cache.test.js')
